# Generated by Django 4.1.1 on 2022-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("stars", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(("stars__range", (1, 100))),
                name="api_person_stars_range",
            ),
        ),
    ]
